name: messio
description: Messio is a modern messaging app

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name iabs used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.16.1
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  infinite_listview: ^1.0.1+1
  firebase_auth: ^0.15.5+2 #to auth with firebase
  google_sign_in: ^4.1.4 #to auth with google account
  flutter_bloc: ^3.2.0 #heedelps in implementing blocs
  equatable: ^0.5.0 #helps in comparing class using their values
  cloud_firestore: ^0.13.4+2 #Firebase Database
  image_picker: ^0.6.3+4 #image picker used for picking images from gallery
  firebase_storage: ^3.1.3 #storage for storing image files
  flutter_launcher_icons: ^0.7.4
  shared_preferences: ^0.5.6+3
  file_picker: ^1.5.0+2
  emoji_picker: ^0.1.0
  video_player: ^0.10.8+1
  flutter_downloader: ^1.4.1
  downloads_path_provider: ^0.1.0
  flushbar: ^1.10.4
  path_provider: ^1.6.5
  cached_network_image: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^4.1.0

flutter_icons:
  ios: true
  android: true
  image_path_ios: "assets/launcher/ic_launcher.png"
  image_path_android: "assets/launcher/ic_launcher.png"
  adaptive_icon_background: "assets/launcher/ic_background.png"
  adaptive_icon_foreground: "assets/launcher/ic_foreground.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  assets:
    - assets/
    - assets/launcher/
    - assets/fonts/
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  fonts:
    - family: Manrope
      fonts:
        - asset: assets/fonts/manrope-regular.otf
        - asset: assets/fonts/manrope-bold.otf
          weight: 700
        - asset: assets/fonts/manrope-extrabold.otf
          weight: 800
        - asset: assets/fonts/manrope-semibold.otf
          weight: 400
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
